### ISSUE TITLE
java.lang.unsatisfiedLinkError

### ISSUE THREAD

**Issue by av-arvind77** [mishraaditya595/ScanIt#42]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vob.scanit, PID: 9196
    java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/app/com.vob.scanit-UfjfEnlsXyn1d-vGYqQN7Q==/lib/arm/libopencv_java4.so" >= file size: 0 >= 0
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.monscanner.ScanActivity.<clinit>(ScanActivity.java:41)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

**Comment by av-arvind77** [comment]
I just run this project in my phone which is MI Redmi 6A. It got installed but while opening camera and files , app crashing.

**Comment by mishraaditya595** [comment]
I guess there must be something in MIUI that is incompatible. Unfortunately, I do not have access to a Xiaomi/Redmi device. Tried it on multiple other phones and have it had worked well.

**Comment by av-arvind77** [comment]
@mishraaditya595 Shall I close this issue or resolve it in MIUI device ?

**Comment by mishraaditya595** [comment]
You can try resolving it

**Comment by mishraaditya595** [comment]
I hope this fixes the issue. If the issue still persists, you can reopen it.
