### ISSUE TITLE
opencv_java4 Not Found Runtime_Exception

### ISSUE THREAD

**Issue by Mukarrim** [mishraaditya595/ScanIt#5]
```
2020-11-02 14:54:41.230 15212-15212/com.vob.scanit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vob.scanit, PID: 15212
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.vob.scanit-LDYqIBvT8zd2uu-7YaDycw==/base.apk"],nativeLibraryDirectories=[/data/app/com.vob.scanit-LDYqIBvT8zd2uu-7YaDycw==/lib/x86, /data/app/com.vob.scanit-LDYqIBvT8zd2uu-7YaDycw==/base.apk!/lib/x86, /system/lib]]] couldn't find "libopencv_java4.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        **at com.monscanner.ScanActivity.<clinit>(ScanActivity.java:41)**
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mishraaditya595** [comment]
I believe you are missing some or all files from the jnilibs folder. Or you are specifying the wrong file in the function.

**Comment by Mukarrim** [comment]
I simply cloned the github repo.

**Comment by mishraaditya595** [comment]
I tried it. It was running perfectly fine.

**Comment by Mukarrim** [comment]
You're right, it only happened with Emulators. Thanks for the great work! 🥇

**Comment by mishraaditya595** [comment]
Thanks for your interest in the project.
